language: c
compiler:
- clang
- gcc
addons:
  apt:
    packages:
    - autoconf
    - autoconf-archive
    - automake
    - python-docutils
    - python-nose
script:
- ./private/autogen
- ./configure
- make
- make test
- find -name "*.rst" | xargs -L1 -t -I{} rst2xml --strict {} /dev/null

# vim:ts=2 sts=2 sw=2 et
