dist: trusty
sudo: false
language: c
compiler:
- clang
- gcc
addons:
  apt:
    packages:
    - cppcheck
    - autoconf
    - autoconf-archive
    - automake
    - python-nose
before_install:
- export PATH=$(echo "$PATH" | tr ':' '\n' | sed -e '/\/opt\/python/d' | tr '\n' ':' | sed 's/::/:/g')
install:
- pip install --user pydiatra
- pip install --user pyflakes
- pip install --user pylint
- pip install --user docutils pygments
script:
- cppcheck --error-exitcode=1 *.c
- ./private/autogen
- ./configure --prefix ~/.local
- make
- make test
- private/check-rst
- python -m pydiatra *.py
- python -m pyflakes *.py
- python -m pylint *.py
- make -C doc
- make install
- cd /
- hungrycat || [ $? -eq 1 ]
- MANPATH=~/.local/share/man MANWIDTH=80 man 1 hungrycat | grep -C 999 -w HUNGRYCAT

# vim:ts=2 sts=2 sw=2 et
