dist: trusty
sudo: false
language: c
compiler:
- clang
- gcc
addons:
  apt:
    packages:
    - cppcheck
    - autoconf
    - autoconf-archive
    - automake
install:
- pip install --user nose
- pip install --user pydiatra pyflakes
- pip install --user pylint
- pip install --user docutils pygments
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- cppcheck --error-exitcode=1 *.c
- ./private/autogen
- ./configure --prefix ~/.local
- make
- make test
- private/check-rst
- python -m pydiatra *.py
- python -m pyflakes *.py
- python -m pylint *.py
- make -C doc
- make install
- cd /
- hungrycat || [ $? -eq 1 ]
- MANPATH=~/.local/share/man MANWIDTH=80 man 1 hungrycat | grep -C 999 -w HUNGRYCAT

# vim:ts=2 sts=2 sw=2 et
