language: c
compiler:
- clang
- gcc
addons:
  apt:
    packages:
    - autoconf
    - autoconf-archive
    - automake
    - python-nose
install:
- pip install --user docutils
script:
- ./private/autogen
- ./configure
- make
- make test
- find -name "*.rst" | xargs -L1 -t -I{} ~/.local/bin/rst2xml.py --strict {} /dev/null

# vim:ts=2 sts=2 sw=2 et
