dist: trusty
sudo: false
language: c
compiler:
- clang
- gcc
addons:
  apt:
    packages:
    - autoconf
    - autoconf-archive
    - automake
    - python-nose
    - python-docutils
    - python-pygments
before_script:
- export PATH=$(echo "$PATH" | tr ':' '\n' | sed -e '/\/opt\/python/d' | tr '\n' ':' | sed 's/::/:/g')
script:
- ./private/autogen
- ./configure
- make
- make test
- private/check-rst

# vim:ts=2 sts=2 sw=2 et
