dist: xenial
language: c
compiler:
- clang
- gcc
addons:
  apt:
    packages:
    - autoconf
    - autoconf-archive
    - automake
    - cppcheck
    - libipc-run-perl
install:
- pip install --user docutils pygments
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- cppcheck --error-exitcode=1 *.c
- ./private/autogen
- ./configure --prefix ~/.local || cat config.log /fail
- make
- make test
- private/check-rst
- make -C doc
- make install
- cd /
- hungrycat || [ $? -eq 1 ]
- MANPATH=~/.local/share/man MANWIDTH=80 man 1 hungrycat | grep -C 999 -w HUNGRYCAT

# vim:ts=2 sts=2 sw=2 et
