dist: trusty
sudo: false
language: c
compiler:
- clang
- gcc
addons:
  apt:
    packages:
    - autoconf
    - autoconf-archive
    - automake
    - python-nose
install:
- pip install --user docutils pygments
- export PATH="$HOME/.local/bin:$PATH"
script:
- ./private/autogen
- ./configure
- make
- make test
- private/check-rst

# vim:ts=2 sts=2 sw=2 et
