language: c
compiler:
- clang
- gcc
before_install:
- sudo apt-get update
- sudo apt-get install -y automake autoconf autoconf-archive python-nose
script:
- ./private/autogen
- ./configure
- make
- make test

# vim:ts=2 sts=2 sw=2 et
