#!/bin/sh

# Copyright © 2016-2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
here=${0%/*}
here=${here#./}
root="$here/../"
root=${root#private/../}
rst2xml=$(command -v rst2xml) \
|| rst2xml=$(command -v rst2xml.py) \
|| { printf 'rst2xml not found\n' >&2; exit 1; }
rst2xml=${rst2xml##*/}
options='--input-encoding=UTF-8 --strict'
if [ $# -eq 0 ]
then
    find "${root}doc" -name '*.rst'
    grep -rwl 'ft=rst' "${root}doc"
else
    printf '%s\n' "$@"
fi |
xargs -t -I{} "$rst2xml" $options {} > /dev/null

# vim:ts=4 sts=4 sw=4 et
