name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - ubuntu-22.04
        cc:
        - gcc
        - clang
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3
    - name: set up APT
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: check changelog syntax
      if: matrix.cc == 'gcc'
      run: |
        dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
    - name: check reST syntax
      if: matrix.cc == 'gcc'
      run: |
        pip install docutils pygments
        private/check-rst
    - name: build the man page
      run: |
        pip install docutils
        make -C doc
    - name: run cppcheck
      if: matrix.cc == 'gcc'
      run: |
        sudo apt-get install cppcheck
        cppcheck --error-exitcode=1 *.c
    - name: check C compiler version
      run: |
        ${{matrix.cc}} --version
    - name: generate autotools stuff
      run: |
        sudo apt-get install autoconf autoconf-archive automake
        ./private/autogen
    - name: configure
      run: |
        ./configure --prefix ~/.local CC=${{matrix.cc}} || cat config.log /fail
    - name: build
      run: |
        make
    - name: run tests
      run: |
        sudo apt-get install libipc-run-perl
        make test
    - name: install
      run: |
        make install
    - name: check whether the executable was installed correctly
      run: |
        cd /
        hungrycat --help
    - name: check whether the man page was installed correctly
      env:
        MANPATH: /home/runner/.local/share/man
        MANWIDTH: 80
      run: |
        cd /
        man 1 hungrycat | grep -A 10 -w HUNGRYCAT

# vim:ts=2 sts=2 sw=2 et
